package email

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
)

const (
	MaxMessageIDLength     = 500
	MaxMessageIDReferences = 50
)

// NewMessageID returns an opaque RFC 5322 Message-ID. The caller supplies a
// host it controls when one is available; invalid or local-only hosts use the
// reserved .invalid namespace instead.
func NewMessageID(host string) (string, error) {
	host = normalizedMessageIDHost(host)
	random := make([]byte, 16)
	if _, err := rand.Read(random); err != nil {
		return "", fmt.Errorf("generate email message id: %w", err)
	}
	return "<opencrm." + hex.EncodeToString(random) + "@" + host + ">", nil
}

// NormalizeMessageID accepts the strict dot-atom-shaped IDs generated by Open
// CRM and the same common shape returned by mailbox providers. Invalid or
// oversized values are ignored instead of making mailbox ingestion fail.
func NormalizeMessageID(value string) string {
	value = strings.TrimSpace(value)
	if len(value) >= 2 && value[0] == '<' && value[len(value)-1] == '>' {
		value = value[1 : len(value)-1]
	}
	if value == "" || len(value)+2 > MaxMessageIDLength || strings.Count(value, "@") != 1 {
		return ""
	}
	for _, character := range value {
		if character <= 32 || character >= 127 || character == '<' || character == '>' {
			return ""
		}
	}
	parts := strings.SplitN(value, "@", 2)
	if !validMessageIDLocalPart(parts[0]) || !validMessageIDHost(parts[1]) {
		return ""
	}
	return "<" + parts[0] + "@" + strings.ToLower(parts[1]) + ">"
}

// ParseMessageIDReferences extracts a bounded, de-duplicated set of IDs from
// an In-Reply-To or References header without retaining arbitrary header text.
func ParseMessageIDReferences(value string) []string {
	result := make([]string, 0)
	seen := make(map[string]struct{})
	for offset := 0; offset < len(value) && len(result) < MaxMessageIDReferences; {
		start := strings.IndexByte(value[offset:], '<')
		if start < 0 {
			break
		}
		start += offset
		end := strings.IndexByte(value[start+1:], '>')
		if end < 0 {
			break
		}
		end += start + 1
		candidate := NormalizeMessageID(value[start : end+1])
		if candidate != "" {
			if _, exists := seen[candidate]; !exists {
				seen[candidate] = struct{}{}
				result = append(result, candidate)
			}
		}
		offset = end + 1
	}
	if len(result) == 0 {
		if candidate := NormalizeMessageID(value); candidate != "" {
			result = append(result, candidate)
		}
	}
	return result
}

func normalizedMessageIDHost(host string) string {
	host = strings.ToLower(strings.TrimSpace(host))
	if host == "localhost" || !validMessageIDHost(host) || !strings.Contains(host, ".") {
		return "open-crm.invalid"
	}
	return host
}

func validMessageIDLocalPart(value string) bool {
	if value == "" || strings.HasPrefix(value, ".") || strings.HasSuffix(value, ".") || strings.Contains(value, "..") {
		return false
	}
	for _, character := range value {
		if (character >= 'a' && character <= 'z') || (character >= 'A' && character <= 'Z') || (character >= '0' && character <= '9') {
			continue
		}
		switch character {
		case '!', '#', '$', '%', '&', '\'', '*', '+', '-', '/', '=', '?', '^', '_', '`', '{', '|', '}', '~', '.':
			continue
		default:
			return false
		}
	}
	return true
}

func validMessageIDHost(host string) bool {
	if host == "" || len(host) > 253 || strings.HasPrefix(host, ".") || strings.HasSuffix(host, ".") {
		return false
	}
	for _, character := range host {
		if (character >= 'a' && character <= 'z') || (character >= 'A' && character <= 'Z') || (character >= '0' && character <= '9') || character == '.' || character == '-' {
			continue
		}
		return false
	}
	for _, label := range strings.Split(host, ".") {
		if label == "" || strings.HasPrefix(label, "-") || strings.HasSuffix(label, "-") {
			return false
		}
	}
	return true
}
